### PR TITLE
VR Support

### PR DESCRIPTION
**Pull request by JonnyOThan**
Make command buffers apply to both eyes
Set the camera transform for both eyes

### CODE REVIEW

**Comment by LGhassen** [comment]
Is it really this simple?

Have you run into other issues or does this make it mostly work?

**Comment by JonnyOThan** [comment]
There are some aliasing issues around the edges of terrain and the sunflares aren't rendering in the right spots.  But this makes it basically usable.

**Comment by LGhassen** [comment]
Alright, merging. Let me know if you need this to be in a release soon or it can wait a bit.

**Comment by JonnyOThan** [comment]
It can wait.  I'd like to get the lens flare issue sorted out but you definitely don't need to wait for that either.  I made a binary available from my fork for anyone who wants to play in VR with scatterer, but I'm pretty sure that's like <5 people.

**Pull request merged**
