### PR TITLE
Resolve Unity errors that show up in debug mode

### PR DESCRIPTION
**Pull request by blowfishpro**
If you run a debug version of the Unity player Unity will throw exceptions for all of these.  I believe doing things that Unity considers unsafe can cause crashes sometimes.

The changes I made should have no impact on the actual functionality.

Also contains a few minor tweaks I needed to get it to compile.

### CODE REVIEW

**Comment by blowfishpro** [comment]
Closing in favor of #79

**Comment by LGhassen** [comment]
@blowfishpro Can you tell me more about running a debug version of the Unity player and what you can do with it? Is this useful for KSP modding?

**Comment by blowfishpro** [comment]
It is definitely useful although I definitely don't use it as much as some others.  It allows the following:
* Using the Unity profiler to measure performance
* Attaching a debugger
* It will actually show line numbers in stack traces provided the `mdb`s are present
* It will complain about unsafe usage of Unity methods which is what I was doing here.

**Comment by LGhassen** [comment]
Hmm, that's definitely interesting. How do I launch KSP in debug mode?

**Comment by blowfishpro** [comment]
If you install Unity, it installs standalone players, if you're on windows what you want can probably be found at something like
```
C:\Program Files\Unity\Editor\Data\PlaybackEngines\windowsstandalonesupport\Variations\win64_development_mono
```
I don't know exactly what all of the components in those things do, as far as I can tell the only thing that's strictly necessary to run KSP in debug mode is the debug UnityPlayer.dll (executables were required previously).

There's some info in this forum topic but it's definitely out of date for Unity 2019/KSP 1.8, some more up-to-date stuff might be in posts near the end of the thread though
https://forum.kerbalspaceprogram.com/index.php?/topic/102909-ksp-plugin-debugging-and-profiling-for-visual-studio-and-monodevelop-on-all-os/

**Comment by LGhassen** [comment]
Thank you

**Pull request closed without merging**
