### PR TITLE
#93 RSSMode

### LINKED ISSUE #93: KSP 1.9.1 RSS Support
Hi,

I have been testing the latest official release with RSS using the same previous configuration it seems it is not working properly. I know R-T-B release supports RSS with a RSSMode. But not sure this release requires a specific configuration for RSS.

Kerbal Space Program 28_04_2020 19_59_08
Kerbal Space Program 28_04_2020 19_58_19

### PR DESCRIPTION
**Pull request by jrodrigv**
Hi,

I added a RSSMode to set correctly the farClipPlane in order to have a proper Earth horizon view distance. This code is based on the @R-T-B fixes for RSS.

I hope this fixes #93

### CODE REVIEW

**Comment by R-T-B** [comment]
setting the farclip was always more of a hack, but if blackrack has no other ideas on how to support Earth-grade horizons, I suppose it could work.  Just my thoughts.  I wish there was a better way, honestly, as you lose a lot of shadow precision setting it out that far.

**Comment by jrodrigv** [comment]
I have uploaded this video where you all visual mods working together in KSP 1.10.1 https://youtu.be/l-xrcI0aiaA

**Comment by LGhassen** [comment]
@jrodrigv what happens when you land on a planet bigger than earth? To which planetary radius does this hold up?

**Comment by jrodrigv** [comment]
> @jrodrigv what happens when you land on a planet bigger than earth? To which planetary radius does this hold up?

Uhmm that is actually interesting. I think the farclip plane should be dynamically calculated depending on the celestial body and the current camera altitude

**Comment by LGhassen** [comment]
This issue is fixed now in 0.0722 without modifying the clip planes, so i'm closing this.

**Pull request closed without merging**
