### PR TITLE
Attempt to make a unified camera build

### PR DESCRIPTION
**Pull request by R-T-B**
This was my attempt to make a modern build with your code that uses unified camera.  It works, but has issues.  I DO NOT expect this to be released like this as it's quite possibly buggy, and frankly, very hacky.  Still, it's a head start!

The biggest issue is lightsources (like engines in some mods) near planets cause the planets to light immensely and sometimes strange checkerboard patterns.  No idea why.  Good luck beyond this, I'm out, did all I could.  Hope it helps! :)

### CODE REVIEW

**Comment by R-T-B** [comment]
The lighting issue is not native, it is caused by engine lights relit and I feel it is an issue with that mod trying to draw intense lights on planets in 1.9.  Ignore my prior comments on that.  I'd advise just removing that mod.

**Comment by R-T-B** [comment]
Blackrack, if you merge this directly, you might want to rollback or at least uncomment that last commit.  It disables terrain shadowing.  I just couldn't cope with the amount of people who weren't following my bugtesting instructions to turn that setting off (since I have no idea how to fix it, heh).

**Comment by R-T-B** [comment]
Just FYI...  I've been doing some testing and for me at least, my hacky shadow code (that was really just raising some projector range numbers) I was so critical of I ripped it all out is...  working?  Needs more testing but it's working well enough for me that i rolled back the shadow disable commit, even for my use.

**Comment by R-T-B** [comment]
This build is now able to target both OpenGL/dual camera modes and single camera modes dynamically.  IT does this using a method in the core class to detect what camera mode it is in and select or discard cameras as appropriate.  It should be very maintainable.  Comments?

If it works on my initial tests, with no obvious regressions, I'll make a release candidate for it soon.

**Comment by R-T-B** [comment]
Working pretty well.  See screenshots below as examples.

DX11 Single camera mode:
DirectX11

OpenGL Dual camera mode (windows):
OpenGL

Same dll.

There is an issue with tracking center sunflares being gone in dual camera I'd like to fix before making an RC.  On it now.

**Comment by R-T-B** [comment]
Fixed the sunflare bug, prepping a new RC for both OpengGL/Nix and DX/WIndows users.

**Comment by jrodrigv** [comment]
Hey! I did a quick test yesterday. I think for standard Kerbin is working good enough (I saw some shadow flickering but I had the shadows active).

However I did a test using RSS and it seems that the farclip plane need to be adjusted using the unified camera (I can see the ocean cut) . I will investigate this

**Comment by R-T-B** [comment]
Yep, I just posted the same on the main issue.  I am working on it too.  Trying a scaling approach using a near clip plane that comes in when it can, coupled with boosting shadow quality to hide the effect...  it's complicated but it might work.

**Comment by R-T-B** [comment]
I think I fixed it.  I did it by using a scaling nearclip plane (based on scene) and it looks pretty dang sharp and good!  It also upped the shadow settings a bit but the performance impact seems low.  I'm curious how this will affect shadows on water though...  up to test?  If not, I will check tomorrow.

Thank you for your help.  Together, we're going to get this done.

**Comment by jrodrigv** [comment]
Uhm for RSS I think farClipPlane 100000f will not be enough due to the horizon distances involved at a real Earth scale. But I will do some testing during the day and I will upload a video :)

Maybe @LGhassen (blackrack)  could give us more info/advice regarding this.

**Comment by R-T-B** [comment]
Well the older builds you were testing were using a clipping plane 10x less than that I think.  Maybe I am mistaken.

Yes, do let me know approximately how bad it is.  With nearclipplane adjustments, I can probably eek out about 2.5x more farclip.  But beyond that, I don;'t know really.  Let's hope we're already somewhat close.

**Comment by LGhassen** [comment]
KSP's stock far clipplane is 750000f if I remember correctly, 100000f seems super low, even for stock, unless you forgot a zero in there.

Now for RSS, let's take an example of Earth, radius is 6000km. Assuming scaledSpace takes over completely at 160km altitude, the maximum distance we need to have visible by the camera is equal to the distance to the tangent point to planet surface from a camera at 160km altitude. Using some geometry we get the value root((6160^2)-(6000^2)) which comes out to 1394km so 1394000f, in practice we can get away with less, due to the scaledSpace mesh filling in for the cropped areas, but a low far plane value is what causes this bug in RSS https://github.com/LGhassen/Scatterer/issues/66

Doing the same calculation for kerbin we get root((760^2)-(600^2)) = 466km so 466000f which is nice although we should probably do this calculation for the largest solid planet in the system (which I think is EVE).

I personally would avoid messing with clipPlanes, both far and near. Sure you try to squeeze out some extra precision but you open yourself up to many other issues, edge cases and a lot of fiddling and is no substitute for fixing the main issue (which I suspect is in the screenSpace shadow shader).

**Comment by R-T-B** [comment]
Yeah I forgot a zero, lol.  I will fix.

**Comment by R-T-B** [comment]
So as of RC10 I feel my quality has reached a level sufficient for a "unofficial release."  The only bug remaining, which is beyond my skill to fix, is of course the shadow shader.  I have workaround for it but I'd love to remove them (they mess with a lot of things that honestly, don't need messing with).  Waiting on @LGhassen to do his magic there.  That is the first priority I'd focus on.

**Comment by LGhassen** [comment]
Hi @R-T-B,

I have added your changes for the planet shader to my 1.9 branch.

For the proper camera returning I have opted to simplify the logic a bit more and replace the farCamera by the nearCamera directly where applicable, and have a simpler method for returning the earliest local camera to render (technically the only reason I need to pick between far or near camera), and make sure I only call this method when initializing and not every frame, although the overhead is technically negligible.

For the sunflare I noticed as well that it doesn't render in front of local scenery anymore, and that the water surface seen from below is broken, both are fixed by this line here: https://github.com/LGhassen/Scatterer/blob/385a6f03c53be45efbd4d7708d135462be38cbf1/scatterer/Utilities/Camera/DepthToDistanceCommandBuffer.cs#L25

I am now working on fixing the flickering shadows (which Squad left for us to fix lol). I will keep looking into your branch and taking the things that seem applicable.

-Blackrack

**Comment by R-T-B** [comment]
Yep, that's what I expected.  My branch is supposed to kind of be a bleeding edge playground for you to refine.  Go get em.

**Comment by LGhassen** [comment]
Hi @R-T-B , I released my official version for 1.9. Only thing I didn't really use is chaning the cameras clipping planes. I'm closing this pull request.

**Pull request closed without merging**
